In [7]:
import numpy as np

# Q1.Create a null vector of size 10 but the fifth value which is 1.

In [28]:
arr = np.eye(1,10,k = 4,dtype = int)
print(arr)

[[0 0 0 0 1 0 0 0 0 0]]


In [30]:
arr1 = (np.arange(10)==4).astype(int)
print(arr1)

[0 0 0 0 1 0 0 0 0 0]


In [34]:
arr2 = np.zeros(10,int)
arr2[4] = 1
print(arr2)

[0 0 0 0 1 0 0 0 0 0]


## Q2. Create a vector with values ranging from 10 to 49.

In [36]:
arr3 = np.arange(10,50)
print(arr3)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


## Q3. Create a 3x3 matrix with values ranging from 0 to 8

In [38]:
arr4 = np.arange(9).reshape(3,3)
print(arr4)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [42]:
from numpy import random
arr5 = np.random.randint(9,size = (3,3))
print(arr5)

[[6 5 3]
 [8 4 5]
 [6 7 8]]


## Q4.  Find indices of non-zero elements from [1,2,0,0,4,0]

In [56]:
arr6 = np.array([1,2,0,0,4,0])
print(np.where(arr6 != 0))

# or

print(np.nonzero(arr6))

(array([0, 1, 4], dtype=int64),)
(array([0, 1, 4], dtype=int64),)


## Q5. Create a 10x10 array with random values and find the minimum and maximum values.

In [71]:
arr7 = np.random.random((10,10))
print('Array:',arr7)
print('\nMinimum:',arr7.min(),'\nMaximum:',arr7.max())

Array: [[0.83267465 0.18258311 0.32487163 0.46502686 0.88969854 0.69780086
  0.26845935 0.26128028 0.76974553 0.61661509]
 [0.41030225 0.91323379 0.53960904 0.47072709 0.24529102 0.939303
  0.26043319 0.38523946 0.55259315 0.32088728]
 [0.10346854 0.19148126 0.36408504 0.45917585 0.29156399 0.65697145
  0.51760748 0.98170772 0.73643667 0.17614025]
 [0.07071164 0.05809912 0.29895446 0.42284071 0.44925041 0.89024198
  0.86815038 0.47906122 0.94909061 0.68938626]
 [0.20549025 0.74138068 0.03847413 0.43205346 0.78097338 0.10857395
  0.74799107 0.90975676 0.47881434 0.28805884]
 [0.62937447 0.87299215 0.07961745 0.59503462 0.25489506 0.62979893
  0.1931558  0.80171155 0.49917776 0.39106649]
 [0.79654017 0.67046914 0.96120682 0.89135215 0.87936781 0.26150415
  0.13365634 0.00518578 0.53897421 0.51885001]
 [0.53455556 0.28839769 0.60218415 0.08598083 0.15410985 0.17126454
  0.52117189 0.81498882 0.80848847 0.01772383]
 [0.15819963 0.15321624 0.388348   0.15369713 0.96178415 0.81560886
  0.198

## Q6. Create a random vector of size 30 and find the mean value.


In [104]:
arr8 = np.random.random(30)
print('Array:',arr8)
print('\nMean:',arr8.mean())

Array: [0.74080102 0.83129568 0.36401976 0.41771905 0.99553493 0.6493991
 0.59904667 0.47056699 0.16194991 0.76689645 0.49145224 0.20630632
 0.27811726 0.62473613 0.2415914  0.29474398 0.35987861 0.23165582
 0.93617321 0.26993491 0.82968044 0.07533556 0.99845856 0.47664338
 0.58196871 0.26601024 0.14002088 0.53299863 0.06100524 0.32075742]

Mean: 0.4738232828987704


In [108]:
arr9 = np.random.randint(10000,size=(30))
print('Array',arr9,'\nMean:',arr9.mean())

Array [3721 5777 9964 4537 8296 8101 1009  154 3738 2766 7840  327 6691  147
 4164 3868 9807 5823 5533 1027 6290  334 6514 8551  764 4093 7739 9542
 9378 7935] 
Mean: 5147.666666666667
